name: DL
on: workflow_dispatch
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
      - run: wget "https://www.google.com/search?client=firefox-b-d&q=%22https%253A%252F%252Fassets.frame.io%252Fencode%252F49737924-0c60-41f1-b2c3-67fef0a66795%252Fh264_1080_best.mp4%253Fx-amz-meta-project_id%253D18b5325f-45c4-4e12-a795-55cc4fcf3b2c%2526x-amz-meta-project_id%253D18b5325f-45c4-4e12-a795-55cc4fcf3b2c%2526x-amz-meta-resource_type%253Dasset%2526x-amz-meta-resource_id%253D49737924-0c60-41f1-b2c3-67fef0a66795%2526Expires%253D1780876800%2526Signature%253DMq9jBErfoHnVynnapX8k7CaN~Nsx-SSgDLY8K7KpRG836xTbptPg~ayvXh-Y15fU9Msl2~5f1RvzO5bOvspHNmARSq-V6ydUQioH9x8PrZSl48TWKF9jOe6B62WDuqxRe9NdLrwHbQSZMH2OstkyUvuqyOu02vSuENOsIB2o6bm32jUGRH7uWVzRtmvAYTxEFM1e-xV~MhF94M~5EAj~EEpirz3KbXCuy6-cwra5sqi8Gp2hfcSXr8G42I1hz4QGPQEtrt9HAbMNHRyUPv8GSNBbB-QVH" -O file
      - uses: actions/upload-artifact@v4
        with:
          name: file
          path: file
